### ISSUE TITLE
problem with multiple db connections

### ISSUE THREAD

**Issue by wedgwood** [fastify/fastify-postgres#10]
The plugin hardcode the name decorated as "pg", then you could not add any other postgres instance into it.

Maybe optional `name` field in option could override the decorating name is nice.

**Comment by mcollina** [comment]
I'm a bit lost why you need to have the same routes connect to two postgres.
Wouldn't registering this within two different plugins work as well?

Anyway, would you mind sending us a PR?

**Comment by wedgwood** [comment]
Hi @mcollina, I give an example,
when visiting an route `/user/:id`, it would visit the db server **A**  for the user's personal info, and visit the db server **B** for the balance of user's account. Now, two postgres server would be visited, then we need two postgres instances. Am i right?

I think there are two way to resolve it, 
1. add name option of plugin decorated to override `pg` hardcoded,  e.g. 
```javascript
fastify.register(require('fastify-postgres'), {
  name: 'a'
  connectionString: 'postgres://postgres@localhost/postgres'
});

fastify.register(require('fastify-postgres'), {
  name: 'b'
  connectionString: 'postgres://postgres@localhost/postgres'
})
```

2. write two plugin myself by copying the repo's code.

I think 1 would be better?

I could send a PR after reaching an agreement :)

**Comment by delvedor** [comment]
I think we should keep the `pg` namespace, would be nice support the name thing as a namespace of `pg`.
For example:
```js
fastify.pg.db1.query
fastify.pg.db2.query
```
The overall complexity of the module will increase, but in my opinion the api is nicer.
What do you think?

**Comment by mcollina** [comment]
it's easier to just provide an option to customize the name of the property. Can you send a PR?

**Comment by wedgwood** [comment]
@mcollina, ok, I will try a PR later. @delvedor I think you are right, the pattern make developer more clear which driver he is using.
