### ISSUE TITLE
Readme.md documentation

### ISSUE THREAD

**Issue by Fedep4lpi** [fastify/fastify-postgres#146]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Why should i also install the pg module in addition to the @fastify/postgres module?

**Comment by Eomm** [comment]
Because you may don't want to use the `pg` module: https://github.com/fastify/fastify-postgres#pg-option

**Comment by climba03003** [comment]
`pg` is not direct dependency of this module. 
If you don't explicitly install it, it may not exist depends on `package manager` or `command`.
