### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by simoroshka** [fastify/fastify-postgres#17]
The plugin does not work with the latest version of Fastify.

`throw new Error(fastify-plugin - expected '${version}' fastify version, '${fastifyVersion}' is installed)
Error: fastify-plugin - expected '>=0.13.1' fastify version, '1.0.0-rc.2' is installed
    at plugin (.../node_modules/fastify-plugin/index.js:24:13)`

**Comment by delvedor** [comment]
Problem related to https://github.com/fastify/fastify-plugin/pull/21 and https://github.com/fastify/fastify/issues/763.
It should be fixed with the latest version of `fastify-plugin`. Can you try to reinstall your dependencies?
