### ISSUE TITLE
Why declare own fastify module with FastifyRequest?

### ISSUE THREAD

**Issue by zettadam** [fastify/fastify-postgres#177]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Maybe it is my ignorance, but in my code Typescript is reading `FastifyRequest` from `@fastify/postgres` instead of `fastify` where I import it from because this package declares its own `fastify` module. It breaks my builds. What can be done to fix that?

![fastify-module](https://github.com/user-attachments/assets/692db09d-2d3d-4800-a47e-e2efb4576243)

**Comment by zettadam** [comment]
Here are TS errors caused by this:

![request params errors](https://github.com/user-attachments/assets/10dcaa0d-c710-4558-a9cc-525d0c999602)

**Comment by mcollina** [comment]
I'm not sure how it broke your build. This technique is called `Declaration Merging`, and it's well documented in the TypeScript website.

https://www.typescriptlang.org/docs/handbook/declaration-merging.html

I think _something else_ might be breaking your build.

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by zettadam** [comment]
In the meantime I used `pg` module directly, but will return to `@fastify/postgres` and will try to post a link to an example. Is there a `fastify` starter available with an online editor? I'm wondering if my `tsconfig.json` might have been a culprit.

**Comment by climba03003** [comment]
The problem is unrelated to `@fastify/postgres`.
You are explicitly typing the `request` as `FastifyRequest` which remove the ability to infer the types from either generic or options (if using type provider).

In a proper way, you should provide the proper types from generic and remove the explicit typing.
```
fastify.get<{ Params: { year: string, month: string, day: string }, Reply: NoteType[] }>(
  '/archive/:year/:month/:day',
  options,
  (request, reply) => {
    const { year, month, day } = request.params
  }
)
```

**Comment by zettadam** [comment]
Yes, I got that working.
