### ISSUE TITLE
connect / release on high frequency endpoints

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify-postgres#21]
I am writing a web mapping framework which uses fastify-postgres in many of the data endpoints. Certain endpoints are hit very frequently (hundreds of times from a single user).

Would you recommend to connect, query and release?

Or would you recommend to connect and store the connection in a global and then just query, query, query.

Both methods are working fine for me but I am concerned the connect handshake is taking time while with the always connected solution I am worried what happens if a connection errs.

**Comment by mcollina** [comment]
Fastify-postgres initialize a connection pool, calling `connect()` is fine.
