### ISSUE TITLE
[enhancement] Utility to start a transaction for every request that commits during onSend

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify-postgres#25]
As the title says

**Comment by cemremengu** [comment]
Should this be enabled by default? If multiple databases are defined in plugin which one should be used? 

Need some pointers for defining the API and behavior

**Comment by mcollina** [comment]
I think it should be enabled by default it there is a single database, and require an option when multiple database are selected. 

A transaction should be started if `reply.query()`  is called, and it should commit it during `onSend`, automatically.

**Comment by cemremengu** [comment]
I was thinking about this and wouldn't it lead to a DoS vulnerability on database if there are too many requests coming in?

**Comment by mcollina** [comment]
Actually this is not a so great idea after all. transact is more than enough.

**Comment by cemremengu** [comment]
I agree, closing this one then
