### ISSUE TITLE
TypeError: fastify.register is not a function

### ISSUE THREAD

**Issue by lynxionxs** [fastify/fastify-postgres#34]
When i use the example code and run ```node server``` i get the error ```TypeError: fastify.register is not a function```
```javascript
const fastify = require('fastify');

fastify.register(require('fastify-postgres'), {
    connectionString: 'postgres://postgres@127.0.0.1/testdb'
});

// ...
```

**Comment by cemremengu** [comment]
You need to init fastify instance first such as

`const fastify = require('fastify')();`

Would you like to send a PR to update docs?

**Comment by lynxionxs** [comment]
Yes the docs need to be updated for that

**Comment by delvedor** [comment]
@lynxionxs you are right! Do you want to send a pr? :)

**Comment by lynxionxs** [comment]
@delvedor i don't know how to do that. You can if you want

**Comment by vallamost** [comment]
What if you want to do an ES6 import?
