### ISSUE TITLE
Update multiple queries example

### ISSUE THREAD

**Issue by lynxionxs** [fastify/fastify-postgres#37]
Can you update the ```pg.transact``` example to use more than one query? Transactions usually have more than one query...

**Comment by cemremengu** [comment]
I think what you are having trouble with is using the `node-postgres` client underneath. Can you see https://node-postgres.com/ if that helps? Once you init the `transact` you can just query like you normally do, nothing special.

**Comment by lynxionxs** [comment]
@cemremengu ah i see , thanks
