### ISSUE TITLE
suggest: use pg-native

### ISSUE THREAD

**Issue by simone-sanfratello** [fastify/fastify-postgres#4]
Hi guys,

I suggest to use pg-native instead of pg, for high performance. It comes with the same interface of pg.

**Comment by billouboq** [comment]
I think this needs to be an option

**Comment by mcollina** [comment]
Passing in an option would be great. Unfortunately the installation of pg-native requires the headers of the native library to be in path.

**Comment by delvedor** [comment]
I'll work on add it as option, if you have some ideas pr are welcome! :)

**Comment by simone-sanfratello** [comment]
I've submitted a pull request (maybe not in the proper branch ...), I did not perform any tests, but the concept should work

**Comment by delvedor** [comment]
Done in https://github.com/fastify/fastify-postgres/pull/7 :)
