### ISSUE TITLE
Add pg as a peer dependency

### ISSUE THREAD

**Issue by MichielDeMey** [fastify/fastify-postgres#42]
Might be better suited for this package to add `pg` as a peer dependency to allow developers to use their preferred version of `pg` and to avoid mixing `pg` versions.

Any specific thoughts on this?

**Comment by cemremengu** [comment]
I think that should be fine, would you like to send a PR?

**Comment by MichielDeMey** [comment]
I'll have a PR up shortly. 👍

**Comment by MichielDeMey** [comment]
Should we follow @mcollina's example and add `pg` as a `devDependency`?
(cfr. https://github.com/brianc/node-pg-pool/blob/master/package.json#L34)

or

Keep it as a main dependency, which means that this library will dictate the `pg` version to be used.

In case of option 1, adding it as a `devDependency` here as well as a `peerDependency` forces developers to specify the `pq` library and version in their main project which could prevent incompatibility issues that would arise from this library dictating the version.

So installation will be `npm install pg fastify-postgres`

Option 1 is not backwards compatible, NPM 3+ will complain in case `pg` is not installed in the main project. So we'll have to bump the major version.
Option 2 is backward compatible, but then this library would dictate the `pg` version with possible incompatibility issues later on.

What's your opinion? (Maybe @mcollina could chime in as well?)

**Comment by mcollina** [comment]
I'm +1 with option 1.

**Comment by cemremengu** [comment]
I think adding it as a devDependency + a peerDependency is better but decision is up to @mcollina

**Comment by mcollina** [comment]
+1 with option 1.
