### ISSUE TITLE
connect is not function 

### ISSUE THREAD

**Issue by babycodes** [fastify/fastify-postgres#58]
### connect is not function 

i try to follow the documentation but i got error .. how can i fix it thanks

### MY FASTIFY CODE
``` javascript
const fastify = require('fastify')()
fastify.register(require('fastify-postgres'), {
  connectionString: 'postgres://username:pass@localhost:5432/db'
})

exports.getAllProduct = async ( req, reply ) => {
	fastify.pg.connect(onConnect)

	function onConnect ( err, client, release ) {
		if ( err ) return reply.send( err )

		client.query(
			'SELECT id, first_name, last_name FROM person',
			function onResult ( err, result ) {
				release()
				reply.send(err || result)
			}
		)
	}
}


```
### THE ERROR
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Cannot read property 'connect' of undefined"
}
```

**Comment by Eomm** [comment]
How you are starting the server?

If you don't call `fastify.listen` or `fastify.ready` the `fastify.pg` will be not set

**Comment by babycodes** [comment]
> How you are starting the server?
> 
> If you don't call `fastify.listen` or `fastify.ready` the `fastify.pg` will be not set

yes i set it fastify.listen on port 3000

**Comment by babycodes** [comment]
its okay when i try to make it on file with server.js but when i try to separate it as controller i can't get the connect function

**Comment by mcollina** [comment]
The following should work:

```js
exports.getAllProduct = async function ( req, reply ) {
         const fastify = this;
	fastify.pg.connect(onConnect)

	function onConnect ( err, client, release ) {
		if ( err ) return reply.send( err )

		client.query(
			'SELECT id, first_name, last_name FROM person',
			function onResult ( err, result ) {
				release()
				reply.send(err || result)
			}
		)
	}
}
```

You still need to register your plugin to the _same_ fastify instance that you use in `server.js`.

**Comment by babycodes** [comment]
> The following should work:
> 
> ```js
> exports.getAllProduct = async function ( req, reply ) {
>          const fastify = this;
> 	fastify.pg.connect(onConnect)
> 
> 	function onConnect ( err, client, release ) {
> 		if ( err ) return reply.send( err )
> 
> 		client.query(
> 			'SELECT id, first_name, last_name FROM person',
> 			function onResult ( err, result ) {
> 				release()
> 				reply.send(err || result)
> 			}
> 		)
> 	}
> }
> ```
> 
> You still need to register your plugin to the _same_ fastify instance that you use in `server.js`.

sorry i'm really new on this
please give me example for it

**Comment by babycodes** [comment]
> The following should work:
> 
> ```js
> exports.getAllProduct = async function ( req, reply ) {
>          const fastify = this;
> 	fastify.pg.connect(onConnect)
> 
> 	function onConnect ( err, client, release ) {
> 		if ( err ) return reply.send( err )
> 
> 		client.query(
> 			'SELECT id, first_name, last_name FROM person',
> 			function onResult ( err, result ) {
> 				release()
> 				reply.send(err || result)
> 			}
> 		)
> 	}
> }
> ```
> 
> You still need to register your plugin to the _same_ fastify instance that you use in `server.js`.

wooow this great WORK LIKE A CHARM

so what that mean this? 
we don' need to declared it again? after we declared from server.js?

**Comment by mcollina** [comment]
The fastify instance is available as `this` in the routes. You need to get the postgres client from the instance you have called `listen()` to, otherwise the plugin will not be loaded.
