### ISSUE TITLE
fastify-postgres: Reason why we cannot use a named connection and an unnamed connection at the same time

### ISSUE THREAD

**Issue by pavish** [fastify/fastify-postgres#72]
I have been upgrading fastify v2 to v3, and along with it, all the plugins we use.

In `fastify-postgres` v2, we were able to use both a named connection and an unnamed connection at the same time. We used `fastify.pg` for the primary db and `fastify.pg.read` for the read replica.

In the latest version, I noticed that there is a restriction placed to prevent such usage. While we are perfectly fine with changing the former to a named connection, I would like to know if there was any reason behind this change. Perhaps a design pattern that I am unaware of, that I would like to know.

Thanks.

**Comment by voxpelli** [comment]
> So it looks like this is an annoying limitation added by adding TypeScript types 😒

No, the types is not to blame here, rather the work with types unveiled some weirdness.

Previously you could add a named connection after an unnamed, but not an unnamed after a named, which was weird.

Taking a closer look, when the named connection was added, it would treat the connection object of the unnamed connection as the collection for named connections, so the named connection would actually be added as a property to the unnamed one in that case, rather than to a collection specifically for named connections (which eg could lead to conflicts of a new property gets added that conflicts with a named connection in an application)

As was suggested in that PR it would be good if access to named and unnamed connections happened through different properties, then the order of adding them wouldn’t matter and none would augment the other anymore.

**Comment by pavish** [comment]
Taking a second look after reading the comment by @voxpelli , I understand the problem.

Would it make sense to modify the code similar to the following:

```
if (!fastify.pg) {
	fastify.decorate('pg', {});
}

if (name) {
	fastify.pg[name] = db;
} else {
	fastify.pg._default = db;
	const props = {};
	Object.keys(db).forEach(key => props[key] = { get: function() { return db[key]; }});
	Object.defineProperties(fastify.pg, props);
}
```

I understand that users with multiple connections would use a separate name, but considering those that start with an unnamed connection and then want to add another connection, it would involve code changes, however small, but slightly inconvenient.

If you guys feel that this might be useful, I could raise a PR for this.

**Comment by voxpelli** [comment]
I don’t see the benefit of having the unnamed and named connections under the same key @pavish 

I would add the named ones to something like `fastify,pgConnections[name]` and leave `fastify.pg` to be for the unnamed connection and nothing else, that way the two can never interfere with one another

**Comment by pavish** [comment]
The only benefit of keeping them both under the same key is that it wouldn't be a breaking change @voxpelli 
In our case, we have a number of services using fastify-postgres and I just wanted to avoid changes throughout. :)

While I agree that having a separate property is cleaner, I would keep them under the same key to prevent it being a breaking change.

But if most of you feel it's better to have a separate property, we can proceed with it.

**Comment by voxpelli** [comment]
@pavish Maybe both 🤔 As it wasn’t intended to be a breaking change in the minor release, we could fix it as is there and then fix it proper in a new major?

Would be good to get a maintainer’s thoughts, ping @mcollina

**Comment by mcollina** [comment]
The change should have been semver-major really but after two months I think it's too late.

As for the reason to support multiple named connections.. I don't understand it in the first place. I use encapsulated plugins to contain only single connection for a chunk of our application. I haven't seen a need to use multiple pg connections within the same route without the need to modify the rest of the code.

Overall I think the code is ok.

**Comment by jsumners** [comment]
> I haven't seen a need to use multiple pg connections within the same route without the need to modify the rest of the code.

It happens. The case of needing a connection to a write available database and a read-replica in the same code is not unheard of.

**Comment by pavish** [comment]
@mcollina I'm sorry, I do not understand your comment. Did you intend to say:

1. The code is fine as it is currently.
2. We can have both named and unnamed connections under the same key, as per the code snippet above.
3. We can have them both under different keys as @voxpelli suggested.

**Comment by mcollina** [comment]
I'm convinced this is a good feature to have... would you mind sending a PR to implement https://github.com/fastify/fastify-postgres/issues/72#issuecomment-766658067?
