### ISSUE TITLE
Coverage 100%

### ISSUE THREAD

**Issue by zekth** [fastify/fastify-postgres#88]
Improve coverage to reach 100%

**Comment by VBetsun** [comment]
During improving code coverage, I recognized that plugin has connection leaks. Currently, [client](https://github.com/fastify/fastify-postgres/blob/8a5d70e9657b88ced9c4360a3593681b5c0893b1/index.js#L139) is being created, and after throwing errors on lines 147, 149, and 155 it doesn't release connection. It is simple to fix by adding `client.release()` before throwing errors.
So, my question is: "Should I fix it in the task of improving code coverage, or do I have to create a new one for this case?"

**Comment by mcollina** [comment]
If the fix is simple enough the same PR is ok. Generally two PRs would be better.

**Comment by Eomm** [comment]
Closed in #105
